# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            plb
tagline:          ''
description:      >
  <p class="lead">
    I'm Paulo Leonardo Benatto, from south Brazil and living in Brighton, UK. Working as 
    Linux Sysadmin, but developer in spare time.
  </p> 
url:              http://patito.github.io
baseurl:          /

author:
  name:           'Paulo Leonardo Benatto'
  url:            https://twitter.com/pbenatto

paginate:         5
