# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            vanz
tagline:          ''
description:      >
  <p class="lead">
  I'm José Guilherme Vanz, from south Brazil. Working as Software Engineer. I love Open Source and programming
  </p>
url:              http://jvanz.github.io
baseurl:          /

author:
  name:           'José Guilherme Vanz'
  url:            https://twitter.com/vanzstuff

paginate:         5
